import Account from "@helpers/faker/account";
import CustomerSelectors from "pages/main/account/setup/customer";
import AlertMessage from "@helpers/utils/alertMessage";
import Button from "@helpers/utils/button";
import Form from "@helpers/utils/form";
import TablePage from "@helpers/utils/table";
import { CommonPageObj } from "@pageObject/commonPageObj/commonPageObj";

let commonPage = new CommonPageObj();
let form = new Form();
let button = new Button();
let alert = new AlertMessage();
let table = new TablePage();
let customerSelector = new CustomerSelectors();
let data = new Account().customer();

class CustomerObj {
  // Method to create a new customer
  createCustomer(filePath: string) {
    cy.task("checkFileExists", filePath).then((bool) => {
      if (!bool) {
        button.clickButton(customerSelector.button().add);
        const promises = [];
        let generatedCode: any;
        for (let key in data) {
          switch (data[key].type) {
            case "autogenerated":
              const promise = form
                .getData(customerSelector.form(key))
                .then((data) => {
                  generatedCode = data;
                });
              promises.push(promise);
              break;
            case "input":
              form.inputField(customerSelector.form(key), data[key].value);
              break;
            default:
              form.getDropdownWithValue(
                customerSelector.form(key),
                data[key].value
              );
              break;
          }
        }

        button.clickButton(customerSelector.button().save);
        cy.wrap(Promise.all(promises)).then(() => {
          cy.writeFile(filePath, {
            ...data,
            code: {
              type: "input",
              value: generatedCode,
            },
          });
          alert.alertMessage(customerSelector.alert().create);
        });
      }
    });
  }

  // Method to search created customer
  searchCustomer(filePath: string) {
    cy.readFile(filePath).then((data) => {
      let customerData = [data.year.value];
      form.inputField(customerSelector.list().search, customerData[0]);
      customerData.forEach((item) => {
        table.tableBody(customerSelector.list().table_td, item);
      });
    });
  }

  // Method to view created customer
  viewCustomer(filePath: string) {
    cy.readFile(filePath).then((data) => {
      let customerData = [data.year.value];
      form.inputField(customerSelector.list().search, customerData[0]);
      button.actions(customerSelector.list().view);

      for (let key in data) {
        switch (data[key].type) {
          case "input":
            commonPage.verifyInputFieldValue(
              customerSelector.form(key),
              data[key].value
            );
            break;
          case "textarea":
            commonPage.verifyInputFieldValue(
              customerSelector.form(key),
              data[key].value
            );
            break;
          default:
            commonPage.verifyCheckUncheck(
              customerSelector.form(key),
              data[key].value
            );
            break;
        }
      }
    });
  }

  // Method to update created customer
  updateCustomer(filePath: string) {
    cy.readFile(filePath).then((data) => {
      let customerData = [data.year.value];
      form.inputField(customerSelector.list().search, customerData[0]);
      button.actions(customerSelector.list().update);

      for (let key in data) {
        switch (data[key].type) {
          case "input":
            form.inputField(customerSelector.form(key), data[key].value);
            break;
          default:
            button.clickSwitch(customerSelector.form(key), data[key].value);
            break;
        }
      }
      button.clickButton(customerSelector.button().save);
      alert.alertMessage(customerSelector.alert().update);
      cy.writeFile(filePath, data);
    });
  }
  // Method to archive created customer
  archiveCustomer(filePath: string) {
    cy.readFile(filePath).then((data) => {
      let customerData = [data.year.value];
      form.inputField(customerSelector.list().search, customerData[0]);
      button.archive(
        customerSelector.delete_confirm().xpath.ok,
        customerSelector.delete_confirm().value.ok
      );
      alert.alertMessage(customerSelector.alert().archive);
    });
  }
}

export default CustomerObj;
