import { faker } from "@faker-js/faker";

import name from "./randomName";
const moment = require("moment");

export class UserManagement {
  designation() {
    let data = {
      name: {
        type: "input",
        value: faker.person.jobTitle().toLowerCase(),
      },
    };
    return data;
  }

  positions() {
    let arr = ["Junior", "Mid", "Senior"];
    let data = {
      name: {
        type: "input",
        value:
          arr[Math.floor(Math.random() * arr.length)] +
          " level " +
          faker.number.int({ min: 10, max: 99 }),
      },
    };
    return data;
  }

  department(dept_type) {
    let data = {
      name: {
        type: "input",
        value: Date.now() + " Dept",
      },
      code: {
        type: "autogenerated",
        value: faker.string.alpha({ length: 3, casing: "upper" }),
      },
      code_prefix: {
        type: "input",
        value: faker.string.alpha({ length: 3, casing: "upper" }),
      },
      display_order: {
        type: "input",
        value: faker.number.int({ min: 10, max: 99 }),
      },

      type: {
        type: "dropdown",
        value: `${dept_type}`,
      },

      length: {
        type: "input",
        value: "3",
      },

      active: {
        type: "switch",
        value: true,
      },
      is_default: {
        type: "switch",
        value: false,
      },

      is_hr: {
        type: "switch",
        value: false,
      },

      is_ward: {
        type: "switch",
        value: false,
      },

      is_diagnostic: {
        type: "switch",
        value: true,
      },

      is_inventory: {
        type: "switch",
        value: false,
      },

      is_clinical: {
        type: "switch",
        value: true,
      },

      is_service: {
        type: "switch",
        value: false,
      },

      is_pharmacy: {
        type: "switch",
        value: false,
      },

      // is_counter: {
      //   type: "switch",
      //   value: false,
      // },
    };
    return data;
  }

  role() {
    let data = {
      name: {
        type: "input",
        value: Date.now() + " role",
      },
    };
    return data;
  }

  user() {
    let password = name.fname + "@123";
    let data = {
      name: {
        type: "input",
        value: name.full_name,
      },
      username: {
        type: "input",
        value: name.fname + faker.number.int({ min: 111, max: 999 }),
      },
      email: {
        type: "input",
        value:
          name.fname.toLowerCase() +
          +faker.number.int({ min: 111, max: 999 }) +
          "@gmail.com",
      },
      password: {
        type: "input",
        value: password,
      },
      password_confirmation: {
        type: "input",
        value: password,
      },
      role: {
        type: "checkbox",
        value: "",
      },
      department: {
        type: "checkbox",
        value: "",
      },
    };

    return data;
  }

  employee() {
    let data = {
      first_name: {
        type: "input",
        value: name.fname,
      },
      middle_name: {
        type: "input",
        value: name.mname,
      },
      last_name: {
        type: "input",
        value: name.lname,
      },
      // nepali_name: {
      //   type: "input",
      //   value: " ",
      // },
      gender: {
        type: "dropdown",
        value: "MALE",
      },

      email: {
        type: "input",
        value: faker.internet.email().toLowerCase(),
      },
      mobile_no: {
        type: "input",
        value: faker.phone.number("98########"),
      },
      department_id: {
        type: "dropdown",
        value: "",
      },
      designation_id: {
        type: "dropdown",
        value: "",
      },
      position_id: {
        type: "dropdown",
        value: "",
      },
      // dob_bs: {
      //   type: "input",
      //   value: "2081-05-23",
      // },
      type: {
        type: "dropdown",
        value: "DOCTOR",
      },
      specilization: {
        type: "input",
        value: faker.lorem.words(2),
      },
      nmc: {
        type: "input",
        value: faker.string.alphanumeric({ length: 7, casing: "upper" }),
      },
      header_caption: {
        type: "input",
        value: faker.lorem.words(2),
      },
      qualification: {
        type: "input",
        value: faker.lorem.words(2),
      },
      nhpc: {
        type: "input",
        value: faker.string.alphanumeric({ length: 7, casing: "upper" }),
      },
      // signature: {
      //   type: "input",
      //   value: {},
      // },
      // profile_image: {
      //   type: "input",
      //   value: {},
      // },
      // employee_details: {
      //   type: "array",
      //   value: [
      //     {
      //       join_date: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
      //       resign_date: null,
      //     },
      //   ],
      // },
      // dob_ad: {
      //   type: "input",
      //   value: "1998-01-01",
      // },
      create_user: {
        type: "switch",
        value: true,
      },
      code: {
        type: "autogenerated",
        value: faker.string.alpha({ length: 7, casing: "upper" }),
      },
    };

    return data;
  }
}

export function employee() {
  let data = {
    first_name: name.fname,
    middle_name: name.mname,
    last_name: name.lname,
    nepali_name: null,
    gender: "Male",
    code: faker.string.alphanumeric(8).toUpperCase(),
    email: faker.internet.email().toLowerCase(),
    mobile_no: faker.phone.number("98########"),
    department_id: null,
    designation_id: null,
    position_id: null,
    dob_bs: "2081-05-25",
    type: "DOCTOR",
    specilization: "Specialization",
    nmc: "nmc",
    header_caption: "header",
    qualification: "qa",
    nhpc: "nhpc",
    create_user: true,
    is_default: false,
    signature: {},
    profile_image: {},
    employee_details: [
      {
        join_date: moment().format("YYYY-MM-DD HH:mm:ss"),
        resign_date: null,
      },
    ],
    dob_ad: "1998-01-01",
  };
  return { data: data };
}
